export const DesciplineList = [
    "Architecture",
    "Structure",
    "Mechanical",
    "Electrical",
    "Plumbing",
    "Fire",
    "Engineering",
    "Planning",
    "Government",
    "Real Estate",
    "Transportation",
    "Natural Resource",
    "Water",
    "Elecrical Gas Utility",
    "Telecommunication",
]