const SoftwareList = [
  "Autodesk Autocad",
  "Autodesk Revit",
  "Tekla",
  "Solid Works",
  "Rhinoceros",
  "Graphisoft Archicad",
  "Vico Software",
  "Synchro Software",
  "Autodesk Naviswork",
  "SketchUp",
  "Autodesk Inside",
  "Energy Plus",
  "ArchiBus",
  "Ecodomes",
  "CAFM explorer",
  "Efacility",
  "FM Services",
  "You BIM",
  "Hexagon Geosystems",
  "Prosoft",
  "Undet",
  "Dynamo",
  "Bluebeam",
  "Autodesk Forge",
  "Chief Architect",
  "Microstation",
  "V-ray",
  "Lumion",
  "Autodesk Maya",
  "Audodesk 3DS-Max",
  "Audodesk Inventor",
  "Enscape",
  "Insite VR",
  "IrisVR",
  "Blender",
  "HAP - Hourly Analysis Program",
  "Pixad",
  "Bentley",
  "RIEGL",
  "iWitness",
  "Whitebox",
  "Arc GIS",
  "Grass GIS",
  "Q GIS",
  "Archmap",
  "Hexgon Geospatial",
  "SAGA",
  "Evan-Society",
  "gv SIG",
  "Tableau",
  "LP 360",
  "Mapinfo Professional",
];

export default SoftwareList;
